FROM node:18-alpine

RUN apk add --no-cache nginx

WORKDIR /app

# Copy package.json and install dependencies
COPY package.json package-lock.json ./
RUN npm install


COPY . .
RUN npm run build
RUN cp -rf ./build ../usr/share/nginx/html
# COPY ./build/ ../usr/share/nginx/html/
ENV PORT=80
EXPOSE 80

# CMD ["npm", "start"]

CMD nginx -g "daemon off;" && npm start --reset-cache






############
# FROM node:18-alpine AS builder

# # Set working directory in the container
# WORKDIR /app

# # Copy package.json and install dependencies
# COPY package.json package-lock.json ./
# RUN npm install

# # Copy all files and build the project
# COPY . .
# RUN npm run build

# # --- Second stage: Nginx for serving the built files ---
# FROM nginx:alpine

# # Copy built React files to Nginx public folder
# COPY --from=builder /app/build /usr/share/nginx/html

# # Expose port 80
# EXPOSE 80

# # Start Nginx
# CMD ["nginx", "-g", "daemon off;"]
