#FROM node:18-alpine as build
#
#WORKDIR /app
#COPY package.json package-lock.json ./
#RUN npm install
#
#COPY . .
#RUN npm run build
#
#FROM nginx:alpine
#
#COPY --from=build /app/build /usr/share/nginx/html
#COPY nginx.conf /etc/nginx/conf.d/default.conf
#
#EXPOSE 80
#
#CMD ["nginx", "-g", "daemon off;"]
FROM alpine:3.19.1

RUN apk update; apk upgrade; apk add nginx; apk add openssl; apk add --no-cache gettext

COPY ./nginx.conf /etc/nginx/nginx.conf

WORKDIR /usr/share/nginx/html

# EXPOSE 4242

CMD ["nginx", "-g", "daemon off;"]
