services:
  # React (Frontend)
  - name: transcendence
    type: web
    runtime: docker
    envVars:
      - fromGroup: ft_transcendence
    dockerfilePath: ./frontend/Dockerfile
    plan: free

  # Django (Backend)
  - name: django
    type: web
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - fromGroup: ft_transcendence
    plan: free