services:
  # NGINX (Reverse Proxy)
  - name: nginx
    type: web
    env: docker
    dockerfilePath: ./nginx/Dockerfile
    envVars:
      - fromFile: .env
    disk:
      - name: media_data
        mountPath: /app/media
    healthCheckPath: /
    startCommand: ''
    autoDeploy: true
    domains:
      - ft_transcendence_kkeklk.com  # Replace with your custom domain
    routes:
      - type: rewrite
        source: /static/*
        destination: /app/static/$1
    dependsOn:
      - django
      - react

  # React (Frontend)
  - name: react
    type: web
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - fromFile: .env
    dependsOn:
      - postgresql
      - django

  # Django (Backend)
  - name: django
    type: web
    env: docker
    dockerfilePath: ./backend/Dockerfile
    startCommand: ./script.sh
    envVars:
      - fromFile: .env
      - key: DATABASE_URL
        value: ${DATABASE_URL}
    disk:
      - name: static_data
        mountPath: /app/static
      - name: media_data
        mountPath: /app/media
    dependsOn:
      - postgresql

  # PostgreSQL (Database)
  - name: postgresql
    type: postgres
    env: docker
    image: postgres:16
    envVars:
      - key: POSTGRES_DB
        value: ${POSTGRES_DB}
      - key: POSTGRES_USER
        value: ${POSTGRES_USER}
      - key: POSTGRES_PASSWORD
        value: ${POSTGRES_PASSWORD}
      - key: POSTGRES_HOST
        value: ${POSTGRES_HOST}
      - key: POSTGRES_PORT
        value: ${POSTGRES_PORT}
    disk:
      - name: postgresql_data
        mountPath: /var/lib/postgresql/data

volumes:
  react_node_modules:
  media_data:
  static_data:
  postgresql_data: