services:
  - name: nginx
    type: web
    env: docker
    dockerfilePath: ./nginx/Dockerfile
    envVars:
      - fromFile: .env
    disk:
      - name: media_data
        mountPath: /app/media
    healthCheckPath: /
    startCommand: ''
    autoDeploy: true
    domains:
      - your-domain.com  # Change to your actual domain
    routes:
      - type: rewrite
        source: /static/*
        destination: /app/static/$1
    dependsOn:
      - django
      - react

  - name: react
    type: web
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - fromFile: .env
    dependsOn:
      - postgresql
      - django

  - name: django
    type: web
    env: docker
    dockerfilePath: ./backend/Dockerfile
    startCommand: ./script.sh
    envVars:
      - fromFile: .env
    disk:
      - name: static_data
        mountPath: /app/static
      - name: media_data
        mountPath: /app/media
    dependsOn:
      - postgresql

  - name: postgresql
    type: database
    env: docker
    image: postgres:16
    envVars:
      - fromFile: .env
      - key: POSTGRES_DB
        value: ${POSTGRES_DB}
      - key: POSTGRES_USER
        value: ${POSTGRES_USER}
      - key: POSTGRES_PASSWORD
        value: ${POSTGRES_PASSWORD}
      - key: POSTGRES_HOST
        value: ${POSTGRES_HOST}
      - key: POSTGRES_PORT
        value: ${POSTGRES_PORT}
    disk:
      - name: postgresql_data
        mountPath: /var/lib/postgresql/data
