services:
  # NGINX (Reverse Proxy)
  - name: nginx
    plan: free
    type: web
    runtime: docker
    envVars:
      - fromGroup: ft_transcendence
    dockerfilePath: ./nginx/Dockerfile
    disk:
        name: media_data
        mountPath: /app/media
    healthCheckPath: /
    autoDeploy: true
    domains:
      - ft-transcendence.com

  # React (Frontend)
  - name: react
    plan: free
    type: web
    runtime: docker
    envVars:
      - fromGroup: ft_transcendence
    dockerfilePath: ./frontend/Dockerfile

  # Django (Backend)
  - name: django
    plan: free
    type: web
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - fromGroup: ft_transcendence
    disk:
        name: static_data
        mountPath: /app/static

databases:
  # PostgreSQL (Database)
  - name: postgresql
    plan: free
    postgresMajorVersion: "16"
    databaseName: karolina1  
    user: karolina1  