services:
  # NGINX (Reverse Proxy)
  - name: nginx
    type: web
    runtime: docker
    dockerfilePath: ./nginx/Dockerfile
    disk:
        name: media_data
        mountPath: /app/media
    healthCheckPath: /
    startCommand: ''
    autoDeploy: true
    domains:
      - ft_transcendence_kkeklk.com

  # React (Frontend)
  - name: react
    type: web
    runtime: docker
    dockerfilePath: ./frontend/Dockerfile

  # Django (Backend)
  - name: django
    type: web
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    startCommand: ./script.sh
    disk:
        name: static_data
        mountPath: /app/static

databases:
  # PostgreSQL (Database)
  - name: postgresql
    databaseName: ${POSTGRES_DB}
    user: ${POSTGRES_USER}