services:
  # NGINX (Reverse Proxy)
  - name: nginx
    type: web
    runtime: docker
    envVars:
      - fromGroup: ft_transcendence
    dockerfilePath: ./nginx/Dockerfile
    # disk:
    #     name: media_data
    #     mountPath: /app/media
    healthCheckPath: /
    autoDeploy: true
    domains:
      - ft-transcendence.com
    plan: free

  # React (Frontend)
  - name: react
    type: web
    runtime: docker
    envVars:
      - fromGroup: ft_transcendence
    dockerfilePath: ./frontend/Dockerfile
    plan: free

  # Django (Backend)
  - name: django
    type: web
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - fromGroup: ft_transcendence
    # disk:
    #     name: static_data
    #     mountPath: /app/static
    plan: free

databases:
  # PostgreSQL (Database)
  - name: postgresql
    plan: free
    postgresMajorVersion: "16"
    databaseName: karolina1  
    user: karolina1  