FROM python:3.9-alpine

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY ./requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt

RUN apk update && apk add --no-cache \
	gcc \
	musl-dev \
	postgresql-dev \
	libffi-dev \
	openssl-dev \
	pkgconfig \
	linux-headers \
	build-base \
	&& apk del build-base


RUN pip install --upgrade pip setuptools wheel \
    && pip install --no-cache-dir debugpy flake8 ipython

COPY . /app/

EXPOSE 8000

RUN chmod +x script.sh

CMD ["./script.sh"]
