# Use the official Python image with Alpine
FROM python:3.9-alpine

# Set environment variables for Python
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Install system dependencies required for building Python packages and database libraries
RUN apk update && apk add --no-cache \
    gcc \
    musl-dev \
    postgresql-dev \
    libffi-dev \
    openssl-dev \
    pkgconfig \
    linux-headers \
    bash \
    git \
    build-base \
    && apk del build-base

# Set the working directory in the container
WORKDIR /code

# Install pip and necessary development dependencies
RUN pip install --upgrade pip setuptools wheel \
    && pip install --no-cache-dir debugpy flake8 ipython

# Copy only the requirements file and install dependencies
COPY ./requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir -r /code/requirements.txt

# Install the package in editable mode
RUN pip install --no-cache-dir -e .

# Expose the port Django will run on
EXPOSE 8000

# Command to run Django's development server with auto-reload enabled
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]

