# Generated by Django 4.1.7 on 2024-11-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('invited', 'Invited'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('blocked', 'Blocked'), ('unblock', 'UnBlocked'), ('removed', 'Removed')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FriendshipHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('previous_status', models.CharField(choices=[('pending', 'Pending'), ('invited', 'Invited'), ('accepted', 'Accepted')], max_length=10)),
            ],
        ),
    ]
