# Generated by Django 4.2.16 on 2024-10-24 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('receiver', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, 
                    related_name='receiver', 
                    to=settings.AUTH_USER_MODEL
                )),
                ('sender', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, 
                    related_name='sender', 
                    to=settings.AUTH_USER_MODEL
                )),
                ('status', models.CharField(
                    choices=[
                        ('pending', 'Pending'),
                        ('invited', 'Invited'),
                        ('accepted', 'Accepted'), 
                        ('rejected', 'Rejected'),
                        ('blocked', 'Blocked'),
                        ('unblock', 'UnBlocked'),
                        ('removed', 'Removed')
                    ], 
                    max_length=10
                )),
            ],
        ),
    ]