# Generated by Django 4.1.7 on 2024-10-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_playerprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar.png', null=True, upload_to='avatars/'),
        ),
    ]
