# Generated by Django 4.1.7 on 2024-11-13 10:53

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_auth_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar.png', null=True, upload_to='', validators=[users.validators.validate_file_size]),
        ),
    ]
