# Generated by Django 4.1.7 on 2024-11-19 19:42

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_login_otp_user_login_otp_used_user_otp_base32_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/avatar.png', null=True, upload_to='avatars/', validators=[users.validators.validate_file_size]),
        ),
    ]
